version: "3.9"

services:
  db:
    image: postgres:14.0
    container_name: dates_db
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
  backend:
    build: ./backend
    container_name: dates_backend
    image: dates-backend
    command: bash -c "chmod +x wait_for_database.sh
      && ./wait_for_database.sh
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db-data: